# Generated by Django 6.0.5 on 2026-05-08 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(db_index=True, help_text='Unique car identifier from Excel (e.g., MIT1000001)', max_length=50, unique=True)),
                ('car_model', models.CharField(blank=True, help_text='Full car model string (e.g., MITSUBISHI 3000GT Z16A [MJGFL6] 1990-2000)', max_length=500)),
                ('steering', models.CharField(blank=True, help_text='Steering type (e.g., LHD, RHD)', max_length=50)),
                ('transmission', models.CharField(blank=True, help_text='Transmission type (e.g., MT, AT)', max_length=50)),
                ('wd', models.CharField(blank=True, help_text='Wheel drive type (e.g., 2WD, 4WD)', max_length=50)),
                ('engine', models.CharField(blank=True, help_text='Engine specification', max_length=255)),
                ('car_parameters', models.TextField(blank=True, help_text='Car parameters (e.g., 3000/4WD/4WS)')),
                ('additional_note', models.TextField(blank=True, help_text='Additional notes (e.g., DOHC(TURBO/4WD/4WS),6FM/T)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
                'ordering': ['car_id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, help_text='Unique group identifier from Excel (e.g., MIT1147463)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['group_id'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Brand name (e.g., Mitsubishi)', max_length=255)),
                ('part_number', models.CharField(db_index=True, help_text='Part number - primary search field (e.g., MQ900871)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='The group this part belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.group')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'parts',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Cross-reference brand name (e.g., Kanoya)', max_length=255)),
                ('brand_number', models.CharField(blank=True, help_text='Cross-reference brand part number (e.g., C13X20)', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who created this basket entry', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(help_text='The selected car', on_delete=django.db.models.deletion.CASCADE, related_name='basket_entries', to='inventory.car')),
                ('part', models.ForeignKey(help_text='The part that was searched', on_delete=django.db.models.deletion.CASCADE, related_name='basket_entries', to='inventory.part')),
            ],
            options={
                'verbose_name': 'Basket Item',
                'verbose_name_plural': 'Basket Items',
                'db_table': 'basket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(help_text='The car in this car-group relationship', on_delete=django.db.models.deletion.CASCADE, related_name='car_groups', to='inventory.car')),
                ('group', models.ForeignKey(help_text='The group in this car-group relationship', on_delete=django.db.models.deletion.CASCADE, related_name='car_groups', to='inventory.group')),
            ],
            options={
                'verbose_name': 'Car-Group Link',
                'verbose_name_plural': 'Car-Group Links',
                'db_table': 'car_groups',
                'unique_together': {('car', 'group')},
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['part_number'], name='idx_part_number'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['group', 'part_number'], name='idx_group_part'),
        ),
    ]
