# Generated by Django 6.0.5 on 2026-05-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_car_metadata_json_importbatch_importrowerror_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='progress_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='stored_file_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
