# Generated by Django 6.0.5 on 2026-05-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_importbatch_failure_reason_importbatch_progress_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('cars', 'Car models'), ('groups', 'Groups and links'), ('parts', 'Part numbers')], default='cars', max_length=20),
        ),
    ]
