# Generated by Django 6.0.5 on 2026-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_basket_basketitem_split'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carattribute',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='part',
            name='idx_group_part',
        ),
        migrations.AlterUniqueTogether(
            name='cargroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carattribute',
            name='car',
        ),
        migrations.RemoveField(
            model_name='part',
            name='group',
        ),
        migrations.RemoveField(
            model_name='cargroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='CarAttribute',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The group ID this basket item belongs to', max_length=50),
        ),
        migrations.AddField(
            model_name='cargroup',
            name='group_id',
            field=models.CharField(db_index=True, default='', help_text='The group ID from Excel (e.g., MIT1147463)', max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='group_id',
            field=models.CharField(db_index=True, default='', help_text='The group ID this part belongs to', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cargroup',
            unique_together={('car', 'group_id')},
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['group_id', 'part_number'], name='idx_group_part'),
        ),
    ]
