# Generated by Django 6.0.5 on 2026-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_cargroup_car_id_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargroup',
            name='group_id',
            field=models.CharField(db_index=True, default='', help_text='The group ID from Excel (e.g., MIT1147463)', max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='group_id',
            field=models.CharField(db_index=True, default='', help_text='The group ID this part belongs to', max_length=255),
        ),
    ]
