# Generated by Django 6.0.5 on 2026-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_increase_group_id_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargroup',
            name='car_id',
            field=models.TextField(db_index=True, default='', help_text='The car identifier (e.g., b7083...)'),
        ),
        migrations.AlterField(
            model_name='cargroup',
            name='group_id',
            field=models.TextField(db_index=True, default='', help_text='The group ID from Excel (e.g., MIT1147463)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='group_id',
            field=models.TextField(db_index=True, default='', help_text='The group ID this part belongs to'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.TextField(db_index=True, help_text='Part number - primary search field (e.g., MQ900871)'),
        ),
    ]
