# Generated by Django 6.0.5 on 2026-06-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_fields_to_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The group ID this basket item belongs to', max_length=255),
        ),
    ]
