# Generated by Django 6.0.5 on 2026-06-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_increase_basketitem_group_id_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='brand',
            field=models.TextField(help_text='Cross-reference brand name (e.g., Kanoya)'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='brand_number',
            field=models.TextField(blank=True, help_text='Cross-reference brand part number (e.g., C13X20)'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='group_id',
            field=models.TextField(blank=True, db_index=True, default='', help_text='The group ID this basket item belongs to'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.TextField(db_index=True, help_text='Unique car identifier from Excel (e.g., MIT1000001)', unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.TextField(blank=True, help_text='Full car model string (e.g., MITSUBISHI 3000GT Z16A [MJGFL6] 1990-2000)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.TextField(blank=True, help_text='Engine specification'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering',
            field=models.TextField(blank=True, help_text='Steering type (e.g., LHD, RHD)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.TextField(blank=True, help_text='Transmission type (e.g., MT, AT)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wd',
            field=models.TextField(blank=True, help_text='Wheel drive type (e.g., 2WD, 4WD)'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='original_file_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='progress_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='sheet_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.TextField(blank=True, help_text='Brand name (e.g., Mitsubishi)'),
        ),
    ]
