# Generated by Django 6.0.5 on 2026-07-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_performance_optimization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('cars', 'Car models'), ('groups', 'Groups and links'), ('parts', 'Part numbers'), ('car_with_parts', 'Car with parts')], default='cars', max_length=20),
        ),
    ]
