# Generated by Django 6.0.5 on 2026-07-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_importbatch_import_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='Import batch that created this row, if any. Used to undo an import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_cars', to='inventory.importbatch'),
        ),
        migrations.AddField(
            model_name='cargroup',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='Import batch that created this row, if any. Used to undo an import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_car_groups', to='inventory.importbatch'),
        ),
        migrations.AddField(
            model_name='part',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='Import batch that created this row, if any. Used to undo an import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_parts', to='inventory.importbatch'),
        ),
    ]
