# Generated by Django 6.0.5 on 2026-07-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_car_import_batch_cargroup_import_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='import_type',
            field=models.CharField(choices=[('cars', 'Car models'), ('groups', 'Groups and links'), ('parts', 'Part numbers'), ('car_with_parts', 'Car with parts'), ('cars_crosscode', 'Cross Code car models'), ('groups_crosscode', 'Cross Code groups and links'), ('parts_crosscode', 'Cross Code part numbers')], default='cars', max_length=20),
        ),
        migrations.CreateModel(
            name='CarCrossCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.TextField(db_index=True, help_text='Unique cross-code car identifier', unique=True)),
                ('car_model', models.TextField(blank=True)),
                ('steering', models.TextField(blank=True)),
                ('transmission', models.TextField(blank=True)),
                ('wd', models.TextField(blank=True)),
                ('engine', models.TextField(blank=True)),
                ('car_parameters', models.TextField(blank=True)),
                ('additional_note', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, help_text='Import batch that created this row, if any. Used to undo an import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_crosscode_cars', to='inventory.importbatch')),
            ],
            options={
                'verbose_name': 'Cross Code Car',
                'verbose_name_plural': 'Cross Code Cars',
                'db_table': 'cars_crosscode',
            },
        ),
        migrations.CreateModel(
            name='CarGroupCrossCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.TextField(db_index=True, default='')),
                ('group_id', models.TextField(db_index=True, default='')),
                ('import_batch', models.ForeignKey(blank=True, help_text='Import batch that created this row, if any. Used to undo an import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_crosscode_car_groups', to='inventory.importbatch')),
            ],
            options={
                'verbose_name': 'Cross Code Car-Group Link',
                'verbose_name_plural': 'Cross Code Car-Group Links',
                'db_table': 'car_groups_crosscode',
                'unique_together': {('car_id', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='PartCrossCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(db_index=True, default='')),
                ('brand', models.TextField(blank=True)),
                ('part_number', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, help_text='Import batch that created this row, if any. Used to undo an import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_crosscode_parts', to='inventory.importbatch')),
            ],
            options={
                'verbose_name': 'Cross Code Part',
                'verbose_name_plural': 'Cross Code Parts',
                'db_table': 'parts_crosscode',
                'indexes': [models.Index(fields=['group_id', 'part_number'], name='idx_group_part_crosscode')],
            },
        ),
    ]
