# Generated by Django 6.0.5 on 2026-07-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_parts_crosscode_norm_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketCrossCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(help_text='Cross-reference brand name (e.g., Kanoya)')),
                ('brand_number', models.TextField(blank=True, help_text='Cross-reference brand part number (e.g., C13X20)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cross Code Basket',
                'verbose_name_plural': 'Cross Code Baskets',
                'db_table': 'basket_crosscode',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'brand_number'), name='uniq_basket_crosscode_brand_pair')],
            },
        ),
        migrations.CreateModel(
            name='BasketItemCrossCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(blank=True, db_index=True, default='', help_text='The group ID this basket item belongs to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.basketcrosscode')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='inventory.carcrosscode')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='inventory.partcrosscode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items_crosscode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross Code Basket item',
                'verbose_name_plural': 'Cross Code Basket items',
                'db_table': 'basket_items_crosscode',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'car', 'part', 'basket'), name='uniq_basket_item_crosscode_user_car_part_basket')],
            },
        ),
    ]
